# Generated by Django 5.2.10 on 2026-01-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo for invoices (recommended: 200x80px)', null=True, upload_to='company_logos/'),
        ),
    ]
