# Generated by Django 5.2.10 on 2026-01-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile_pics/'),
        ),
    ]
