# Generated by Django 5.2.10 on 2026-01-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='delivery_method',
            field=models.CharField(choices=[('home_delivery', 'Home Delivery'), ('pickup', 'Pickup from Warehouse')], default='home_delivery', help_text='How would you like to receive the product?', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='delivery_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
